### ISSUE TITLE
フルスクリーン時の終了方法

### ISSUE THREAD

**Issue by Reputeless** [sashi0034/Sukuu#2]
`Window::SetFullscreen(true);` と `System::SetTerminationTriggers(UserAction::CloseButtonClicked);` の組み合わせによって、通常のプレイでは alt + Enter を押してウィンドウを表示する以外終了できなさそうな気がしますがあってますか。終了方法がわからずタスクマネージャーから閉じてしまいました。

**Comment by sashi0034** [comment]
Winキーでタスクバーを出してゲームを終了していただく想定でした
確かにタイトル画面に終了ボタンいれるなどの工夫があったほうがよさそうですね

**Comment by sashi0034** [comment]
実装したりしました
