### ISSUE TITLE
フォント基本サイズの引き上げ

### ISSUE THREAD

**Issue by Reputeless** [sashi0034/Sukuu#3]
<img width="81" alt="image" src="https://github.com/sashi0034/Sukuu/assets/3108136/f8b5ba93-f0a3-49be-9542-82278e8d5275">

<img width="103" alt="image" src="https://github.com/sashi0034/Sukuu/assets/3108136/1742653c-3479-4b00-87f1-932b10aa6a1d">

上記のような細部のつぶれた文字が意図した表現でなければ、フォントの基本サイズを引き上げることで精細にできます。

おそらく SDF フォントを使っていると思いますが、SDF / MSDF での日本語フォントの推奨基本サイズは 40～48 です。

また、SDF でなく MSDF フォントを使うことで、文字の角が丸くなるのを防ぐことができます。
- チュートリアル 31.10 https://siv3d.github.io/ja-jp/tutorial2/font/

基本サイズの引き上げや MSDF の使用に伴い、文字初回描画時の一瞬の負荷が気になる場合は、プリロードを使用すると良いです。
- チュートリアル 31.23 https://siv3d.github.io/ja-jp/tutorial2/font/

**Comment by sashi0034** [comment]
なるほど、SDFフォントの推奨サイズについて存じ上げておりませんでした
修正して文字表現がよくなりました。ありがとうございます
https://github.com/sashi0034/Sukuu/commit/d331f8e4077dd54c1c19850190e917bf819e8a07
